[default]
DEBUG = false
TESTING = false
LOG_DIR = 'log/'
LOG_FORMAT = '[%(asctime)s] %(levelname)s in %(module)s/%(funcName)s/%(lineno)d: %(message)s'
LOG_LEVEL = "INFO"
LOG_FILE_NAME = 'flask_app.log'

[development]
SQLALCHEMY_TRACK_MODIFICATIONS = false
LOG_LEVEL = "DEBUG"
DEBUG = true
TESTING = true

[staging]

[testing]

[production]
